# Automatically generated by zkbd.
typeset -g -A key

key[F1]='^[OP'
key[F2]='^[OQ'
key[F3]='^[OR'
key[F4]='^[OS'
key[F5]='^[[15~'
key[F6]='^[[17~'
key[F7]='^[[18~'
key[F8]='^[[19~'
key[F9]='^[[20~'
key[F10]='^[[21~'
key[F11]=''''
key[F12]='^[[24~'
key[Backspace]='^?'
key[Insert]='^[[2~'
key[Home]='^[[1~'
key[PageUp]='^[[5~'
key[Delete]='^[[3~'
key[End]='^[[4~'
key[PageDown]='^[[6~'
key[Up]='^[[A'
key[Left]='^[[D'
key[Down]='^[[B'
key[Right]='^[[C'
key[Menu]=''''

# Load required widgets
#autoload insert-composed-char
#autoload edit-command-line

# insert-composed-char doesn't seem to work
#zle -N edit-command-line
#zle -N insert-composed-char

bindkey $key[Delete] delete-char
bindkey $key[Backspace] backward-delete-char

bindkey "^W" backward-delete-word
bindkey "^Q" delete-word

bindkey $key[Right] forward-char
bindkey $key[Left] backward-char

bindkey $key[Up] history-beginning-search-backward
bindkey $key[Down] history-beginning-search-forward
bindkey "^S" history-incremental-search-forward
bindkey "^R" history-incremental-search-backward

bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey $key[Home] beginning-of-line
bindkey $key[End] end-of-line

bindkey "^H" backward-word
bindkey "^L" forward-word

bindkey "^K" kill-line
bindkey "^U" kill-whole-line

bindkey "^S" clear-screen

